### ISSUE TITLE
Script doesnt work

### ISSUE THREAD

**Issue by X-Kill26** [mudachyo/X-Empire#5]
Script doesnt work
![2024-09-21_133147](https://github.com/user-attachments/assets/203d6349-cde6-43f2-be42-192d820e667a)

**Comment by mudachyo** [comment]
work

**Comment by X-Kill26** [comment]
Привет! Объясни пожалуйста, как правильно запустить, делаю все по инструкции, у меня экран как на скриншоте, не работает бот

Hello! Please explain how to launch correctly, I do everything according to the instructions, my screen is like in the screenshot, the bot does not work

**Comment by mudachyo** [comment]
> Привет! Объясни пожалуйста, как правильно запустить, делаю все по инструкции, у меня экран как на скриншоте, не работает бот
> 
> Hello! Please explain how to launch correctly, I do everything according to the instructions, my screen is like in the screenshot, the bot does not work

Попробуй использовать другой браузер
