### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by lolminerxmrig** [mudachyo/X-Empire#6]
HI.
me try not working.

**Comment by mudachyo** [comment]
working

**Comment by lolminerxmrig** [comment]
not working.
plz fixed

**Comment by lolminerxmrig** [comment]
![image](https://github.com/user-attachments/assets/fd1a1108-1461-40c3-b4f6-9c481e4cc961)

**Comment by mudachyo** [comment]
Working.

Отправлено с iPhone

**Comment by lolminerxmrig** [comment]
![image](https://github.com/user-attachments/assets/02878c2d-f1d3-4969-aee2-998201753fe4)
