### ISSUE TITLE
i can't delete the script

### ISSUE THREAD

**Issue by whyple** [mudachyo/X-Empire#8]
I can't delete the script. I have already deleted the script and extension, but when I press F12, a panel with device selection still appears, as in the script

**Comment by mudachyo** [comment]
Это делает не скрипт, а панель в браузере

**Comment by whyple** [comment]
нет, вы не поняли. как мне это удалить? типо эта фигня с выбором устройства "iphone 14 pro" и тд. как мне ее удалить?

**Comment by mudachyo** [comment]
> нет, вы не поняли. как мне это удалить? типо эта фигня с выбором устройства "iphone 14 pro" и тд. как мне ее удалить?

Так же, как вы включали этот режим.
С открытой консолью нажать Ctrl + Shift + M

**Comment by whyple** [comment]
спасибо
